# Generated by Django 6.0.2 on 2026-03-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ecommerce', '0001_initial'), ('ecommerce', '0002_productmodel_color_productmodel_description_and_more'), ('ecommerce', '0003_productmodel_short_description'), ('ecommerce', '0004_remove_productmodel_short_description')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.FloatField()),
                ('color', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_dimensions', models.TextField(blank=True, null=True)),
                ('seller', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
