# Generated by Django 6.0.2 on 2026-03-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_squashed_0004_add_changes_and_delated_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_dimensions',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='seller',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('BR', 'BORRADOR'), ('PU', 'PUBLICADO'), ('PR', 'PRIVADO')], default='BR', max_length=2),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
