# Generated by Django 6.0.2 on 2026-03-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_productmodel_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('PU', 'PUBLICADO'), ('BR', 'BORRADOR'), ('PR', 'PRIVADO')], default='BR', max_length=2),
        ),
    ]
